### ISSUE TITLE
StrictMode: A resource was acquired at attached stack trace but never released

### ISSUE THREAD

**Issue by nshmura** [SIROK/growthbeat-android#76]
細かいところですが、StrictModeを有効にしているとワーニングが出るようです。

```
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
              java.lang.Throwable: Explicit termination method 'close' not called
                  at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                  at java.io.FileOutputStream.<init>(FileOutputStream.java:89)
                  at android.app.ContextImpl.openFileOutput(ContextImpl.java:393)
                  at android.content.ContextWrapper.openFileOutput(ContextWrapper.java:183)
                  at com.growthbeat.Preference.saveFile(Preference.java:113)
                  at com.growthbeat.Preference.save(Preference.java:93)
                  at com.growthbeat.model.Client.save(Client.java:43)
                  at com.growthbeat.Growthbeat$1.run(Growthbeat.java:119)
                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                  at java.lang.Thread.run(Thread.java:818)
```

**Comment by sangotaro** [comment]
#83
